### ISSUE TITLE
stuck on xbox logo

### ISSUE THREAD

**Issue by Leerz** [StelioKontosXBL/AuroraCrashPatcher#2] opened 2021-04-25 15:42 UTC
trying this out, added it as plugin inside dashlaunch
when i reboot i'm stuck on the xbox360 logo
i mount the drive on windows with fatxplorer to remove the plugin entry and no stuck on logo anymore.

maybe i'm doing something wrong

**Comment by Makein** [comment] 2021-04-26 05:37
> 
> 
> trying this out, added it as plugin inside dashlaunch
> when i reboot i'm stuck on the xbox360 logo
> i mount the drive on windows with fatxplorer to remove the plugin entry and no stuck on logo anymore.
> 
> maybe i'm doing something wrong


You need only blank (Or same, but without AuroraCrashPatcher.xex) launch.ini on root of usb to bypass hdd1:\launch.ini

https://www.youtube.com/watch?v=l7Uxc8p3L2k


Last version freeze for me too (no other plugins enabled)
Try 0.3 beta
And yes liveblock\strong disabled in dashlaunch

**Comment by Ste1io** [comment] 2021-04-26 21:24
I'm unable to reproduce this on my end, but I think I know what's causing this issue. Does it still happen on this last commit? (Direct download: https://github.com/StelioKontosXBL/AuroraCrashPatcher/blob/main/Dist/AuroraCrashPatcher.xex)

**Comment by StelioKontosXBL** [comment] 2021-04-28 21:44
@Makein Most likely that was being caused from your kernel build. I've updated the patch to run on older dashboards prior to 17559; if you get a chance to test this version and confirm if this fixes the issue I'd appreciate it. Download it from https://github.com/StelioKontosXBL/AuroraCrashPatcher/tree/main/Dist.

**Comment by StelioKontosXBL** [comment] 2021-04-28 22:06
> trying this out, added it as plugin inside dashlaunch
> when i reboot i'm stuck on the xbox360 logo
> i mount the drive on windows with fatxplorer to remove the plugin entry and no stuck on logo anymore.
> 
> maybe i'm doing something wrong

Most likely that was being caused from your kernel build. I've updated the patch to run on older dashboards prior to 17559; if you get a chance to test this version and confirm if this fixes the issue I'd appreciate it. Download it from https://github.com/StelioKontosXBL/AuroraCrashPatcher/tree/main/Dist.

**Comment by Ste1io** [comment] 2021-04-28 22:06
> trying this out, added it as plugin inside dashlaunch
> when i reboot i'm stuck on the xbox360 logo
> i mount the drive on windows with fatxplorer to remove the plugin entry and no stuck on logo anymore.
> 
> maybe i'm doing something wrong

@Leerz Most likely that was being caused from your kernel build. I've updated the patch to run on older dashboards prior to 17559; if you get a chance to test this version and confirm if this fixes the issue I'd appreciate it. Download it from https://github.com/StelioKontosXBL/AuroraCrashPatcher/tree/main/Dist.

**Comment by Ste1io** [comment] 2021-04-29 12:45
Closing this issue as v1.2 is now confirmed to resolve this.

**Closed as completed by Ste1io** 2021-04-29 12:45 UTC

**Comment by Leerz** [comment] 2021-05-02 12:09
no crashes so far on 3 xboxes, they were all 17510 - (even the ones that were crashing before)
excellent tysvm

**Comment by Ste1io** [comment] 2021-05-04 16:58
Wonderful glad to hear. Thanks for the update,
