### ISSUE TITLE
'unhandled exception' still popping up.

### ISSUE THREAD

**Issue by Zayddd** [StelioKontosXBL/AuroraCrashPatcher#6] opened 2021-05-06 08:37 UTC
extracted it via USB,

edited my launch.ini file, i go to the refresh button in Aurora and attempt to refresh to download assets, boxart, screenshots, etc etc, and still gives me an error.

Note: im located in Australia, if that helps. :)

**Comment by Makein** [comment] 2021-05-06 08:57
Update dash, go to dashlaunch installer, disable all live blocking options, add as plugin AuroraCrashPatcher, save it through dashlaunch. Reboot, go and do scan. All work

**Comment by Ste1io** [comment] 2021-05-06 11:05
@Zayddd grab the debug version in the "Dist" folder of this repo, and rescan titles after rebooting. If you get the unhandled exception again, drop the log file it makes on your Hdd root here along with your launch.ini.

After the issue is resolved, you'll want to switch back to the regular distribution xex.

**Comment by TempAccountNull** [comment] 2021-06-07 09:03
> 
> 
> @Zayddd grab the debug version in the "Dist" folder of this repo, and rescan titles after rebooting. If you get the unhandled exception again, drop the log file it makes on your Hdd root here along with your launch.ini.
> 
> After the issue is resolved, you'll want to switch back to the regular distribution xex.

Hi, I'm an Aurora developer, can you let me know what your discord is, so we can push an updated build out? Thanks man.

**Comment by Ste1io** [comment] 2021-06-11 03:21
> Hi, I'm an Aurora developer, can you let me know what your discord is, so we can push an updated build out? Thanks man.

@TempAccountNull Sorry for this late response, been fairly busy on a couple other projects lately and just saw your message tonight. Drop me a message at Stelio#5497 on discord at your convenience and I'll be happy to help.

**Comment by ileathan** [comment] 2021-08-21 13:00
Although I did spend a few hours on this issue and OP never actually replied, should be closed as all I had to do was reboot lol. I bet him too. Thanks immensely for this plugin btw, can 1 click download entire asset databases again.

**Comment by TannerH34** [comment] 2021-09-08 08:40
> > @Zayddd grab the debug version in the "Dist" folder of this repo, and rescan titles after rebooting. If you get the unhandled exception again, drop the log file it makes on your Hdd root here along with your launch.ini.
> > After the issue is resolved, you'll want to switch back to the regular distribution xex.
> 
> Hi, I'm an Aurora developer, can you let me know what your discord is, so we can push an updated build out? Thanks man.

This is rather unrelated but when i open my hdd in the file manager in aurora my xbox freezes. any ideas what could cause that? everything else in aurora works perfectly excet that.

**Comment by TannerH34** [comment] 2021-09-08 08:42
> > > @Zayddd grab the debug version in the "Dist" folder of this repo, and rescan titles after rebooting. If you get the unhandled exception again, drop the log file it makes on your Hdd root here along with your launch.ini.
> > > After the issue is resolved, you'll want to switch back to the regular distribution xex.
> > 
> > 
> > Hi, I'm an Aurora developer, can you let me know what your discord is, so we can push an updated build out? Thanks man.
> 
> This is rather unrelated but when i open my hdd in the file manager in aurora my xbox freezes. any ideas what could cause that? everything else in aurora works perfectly excet that.

i should mention thats with the aurora crash  patcher

**Closed as completed** 2021-11-21 21:14 UTC
