### ISSUE TITLE
Is not working outside US

### ISSUE THREAD

**Issue by ghost** [StelioKontosXBL/AuroraCrashPatcher#1] opened 2021-04-22 16:49 UTC
Hi there,

I have tried your patch in my console, but it seems is still no working for people outside US. I have activated livestrong: ON like DaCukiMonsta mentioned in his post and is now working.  

Best regards,

Daniel

**Comment by Makein** [comment] 2021-04-22 18:18
For me it works (partly)
I now can dl all covers, but crash still appear every launch.
I try it on  clean install of  fsd3&aurrora

**Comment by Ste1io** [comment] 2021-04-23 00:10
I added a debug version; can both of you replace the patch xex you're currently using with the debug xex, and send the output you get in Xbox Watson when you crash (liveblock/livestrong should be disabled).

Ideally, select the "download" option under Aurora/Settings/Assets/Update Assets, with all assets checked (icons/boxart/banners/backgrounds/trailers/screenshots). Note for me also which marketplace locale is selected, please.

**Comment by Ste1io** [comment] 2021-04-23 00:24
Also, is this issue happening in Aurora, FSD, or both?

**Comment by ghost** [comment] 2021-04-23 04:32
> I added a debug version; can both of you replace the patch xex you're currently using with the debug xex, and send the output you get in Xbox Watson when you crash (liveblock/livestrong should be disabled).
> 
> Ideally, select the "download" option under Aurora/Settings/Assets/Update Assets, with all assets checked (icons/boxart/banners/backgrounds/trailers/screenshots). Note for me also which marketplace locale is selected, please.

Hi @StelioKontosXBL I don't know what you mean by xbox watson.

1. I have disabled again liveblock, livestrong, updated to the debug-patch with Dashlaunch 3.21 with the last kernel
2. Copy a fresh version of Aurora 0.7b1 to my HDD
3. Select path for games in Content/0000.... and then, after scanning crash
4. Marketplace locale is: Mexico (Spanish)
5. All the assets are selected
6. After restart Aurora, I press the Download button and then crash again.
7. I have attached a copy of my Logs in the fresh aurora version, link: https://drive.google.com/drive/folders/1iwA2XnwB2SxilhxRj2DwPLjhhWcaNC--?usp=sharing

Optional:

If you upload the logs file in xboxunity in the "Read log" option, you will see where are the errors.

![image](https://user-images.githubusercontent.com/35694200/115820182-f2a95300-a3c5-11eb-9a25-a6cf6cc2b3a3.png)

![image](https://user-images.githubusercontent.com/35694200/115819906-6b5bdf80-a3c5-11eb-8cf5-c74ff4318224.png)

**Comment by Makein** [comment] 2021-04-23 07:06
Same as above, only Marketplace locale is: USA (Try UK and RUSSIA, same result)
With and without liveblock/livestrong disable.
Logs: https://drive.google.com/file/d/1WgCScIHnhDpf7KcKIuhj8fgl9VJYMpVj/view?usp=sharing

**Comment by Ste1io** [comment] 2021-04-24 00:30
Could you guys send a screenshot of your plugins, or your launch.ini? Sounds like the plugin isn't loading at all; possibly a conflict with some other plugin on the console.

**Comment by Ste1io** [comment] 2021-04-24 00:40
If you have Neighborhood installed, watson will be installed already btw. Just make sure your console is set as default in neighborhood, then type "watson" in the start menu and it should come right up.
![devenv_0b43rZsm9F](https://user-images.githubusercontent.com/37424493/115941614-e7543700-a45a-11eb-9c6e-f004dadf2230.png)

**Comment by ghost** [comment] 2021-04-24 02:18
> If you have Neighborhood installed, watson will be installed already btw. Just make sure your console is set as default in neighborhood, then type "watson" in the start menu and it should come right up.
> ![devenv_0b43rZsm9F](https://user-images.githubusercontent.com/37424493/115941614-e7543700-a45a-11eb-9c6e-f004dadf2230.png)

Hi @StelioKontosXBL 

Launch file: https://drive.google.com/file/d/1T1YG7eAIVCsTgWy6hQpKVEtR69gxu5lv/view?usp=sharing 

<img width="960" alt="launch" src="https://user-images.githubusercontent.com/35694200/115944031-242f2680-a479-11eb-998f-35bfe7bd9ac8.png">

Crash output xbox watson file (dump): https://drive.google.com/file/d/1X_y26s2q04dNOaD9-di8L79HdvnkIA_v/view?usp=sharing 

Crash 1
<img width="960" alt="crash watson" src="https://user-images.githubusercontent.com/35694200/115944083-53459800-a479-11eb-9eba-c4fd817630a2.png">

Crash2
<img width="960" alt="crash2" src="https://user-images.githubusercontent.com/35694200/115944082-53459800-a479-11eb-8666-43b2abb068b4.png">

Crash3
<img width="960" alt="crash3" src="https://user-images.githubusercontent.com/35694200/115944084-53459800-a479-11eb-894a-2bf08372bd23.png">
 
Crash4
<img width="960" alt="crash4" src="https://user-images.githubusercontent.com/35694200/115944273-67d66000-a47a-11eb-9e07-0e5fa40b8772.png">

**Comment by Ste1io** [comment] 2021-04-24 03:05
@danielTobon43 Are you hitting that exception when scanning titles for artwork, or when Aurora is launched? I'm not seeing any of my debug prints in there; you should be seeing something like this: 

```
Connecting to 192.168.137.69...
Connected to Jtag (192.168.137.69).
[sk] Detected DNS Lookup for "xboxunity.net"
[sk] Detected DNS Lookup for "catalog.xboxlive.com"
[sk] Detected DNS Lookup for "catalog.xboxlive.com"
OPEN_ALWAYS
CreateFile: f8000100 - 00000004 -10000080
OPEN_ALWAYS
CreateFile: f8000104 - 00000004 -10000080
[sk] Detected DNS Lookup for "xboxunity.net"
OPEN_ALWAYS
CreateFile: f800010c - 00000004 -10000080
OPEN_ALWAYS
CreateFile: f8000110 - 00000004 -10000080
[sk] Detected DNS Lookup for "catalog.xboxlive.com"
[sk] Detected DNS Lookup for "catalog.xboxlive.com"
[sk] Blocked DNS Lookup for "download.xbox.com"
[sk] Blocked DNS Lookup for "download.xbox.com"
[sk] Blocked DNS Lookup for "download.xbox.com"
[sk] Blocked DNS Lookup for "download.xbox.com"
[sk] Blocked DNS Lookup for "download.xbox.com"
[sk] Blocked DNS Lookup for "download.xbox.com"
[sk] Blocked DNS Lookup for "download.xbox.com"
[sk] Blocked DNS Lookup for "download.xbox.com"
[sk] Blocked DNS Lookup for "download.xbox.com"
[sk] Blocked DNS Lookup for "download.xbox.com"
[sk] Blocked DNS Lookup for "download.xbox.com"
[sk] Blocked DNS Lookup for "download.xbox.com"
```

**Comment by ghost** [comment] 2021-04-24 03:34
I got that exception when I press refresh on a game. It seems that your plugin is not properly setup on my xbox? I have already added it in my launch.ini with dashlaunch, I don't know what is the problem

**Comment by ghost** [comment] 2021-04-24 03:57
I was reading on the internet that these type of tools like xbox watson only works in a DEV kernel, I don't think I have it. My kernel is standard since I don't develop programs for the xbox.

**Comment by Ste1io** [comment] 2021-04-25 02:51
Watson is designed to work for standard retail RGH consoles, which is what you are using. Looks like the plugin is not loading; most likely due to a base address conflict with another plugin. Otherwise you would have seen the `[sk] ...` debug messages being emitted from the patch xex. I'll make a branch and change the base address and have you try that if you don't mind.

**Comment by Ste1io** [comment] 2021-04-25 03:18
@danielTobon43 @Makein Would you both be so kind as to test this build: https://github.com/StelioKontosXBL/AuroraCrashPatcher/tree/base-addr-tests/Dist.

**Comment by ghost** [comment] 2021-04-25 04:14
Hi @StelioKontosXBL 

I got this output:

```
System.Runtime.InteropServices.COMException (0x82DA0100): Exception from HRESULT: 0x82DA0100
   at XDevkit.XboxConsoleClass.get_Name()
   at xbWatson.BreakHandler.ShowDialog(IXboxEventInfo eventInformation, String middleButtonText)
   at xbWatson.CrashHandler.HandleEvent(IXboxEventInfo eventInformation)
   at xbWatson.DebugManager.HandleEvent(XboxDebugEventType eventCode, IXboxEventInfo eventInformation)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.9031 (WinRelRS5.050727-9000)
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v2.0.50727/mscorlib.dll
----------------------------------------
xbWatson
    Assembly Version: 1.0.4996.31978
    Win32 Version: 2.0.21256.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Microsoft%20Xbox%20360%20SDK/bin/win32/xbwatson.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.9031 (WinRelRS5.050727-9000)
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Windows.Forms/2.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.9031 (WinRelRS5.050727-9000)
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.9031 (WinRelRS5.050727-9000)
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Drawing/2.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
XDevkit
    Assembly Version: 2.0.21256.0
    Win32 Version: 2.0.21256.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Microsoft%20Xbox%20360%20SDK/bin/win32/XDevkit.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

**Comment by Ste1io** [comment] 2021-04-25 05:56
@danielTobon43 Just try running it without watson initially, and see if it prevents the crash when refreshing a title.

**Comment by ghost** [comment] 2021-04-25 11:30
Hi @StelioKontosXBL I have tried the new plugin without watson and I think is working partially. For some title everything download normally and for other games crash. But this is refreshing each game one by one. If I press download button in multimedia for all the games, then crash immediately. I think is because the number of requests for each title. I have about 95 games.

**Comment by Ste1io** [comment] 2021-04-25 14:01
> Hi @StelioKontosXBL I have tried the new plugin without watson and I think is working partially. For some title everything download normally and for other games crash. But this is refreshing each game one by one. If I press download button in multimedia for all the games, then crash immediately. I think is because the number of requests for each title. I have about 95 games.

Sounds like it still isn't loading. All titles use the same domains to retrieve the actual IP address used to download the assets, so if it works on some it will work on all of them. Some titles don't request assets from Microsoft's CDN (such as homebrew apps), and those would not trigger the fatal exception even without the patch loaded.

The api requests are added to a worker thread queue and pumped out as downloads are complete, so the number of requests shouldn't be an issue (a complete scan on my console starts with ~200 downloads, and I've tested it on hard drives with ~300 titles/600+ downloads with no issues).

I'm updating the xex at the link I gave you with another version without a set base address; note that some features in your guide (like sending messages) may not function while using this xex, but it's pretty much guaranteed to load so if it works I'll know what to change for a final release update.

**Comment by Ste1io** [comment] 2021-04-25 14:53
@danielTobon43 Updated the branch with new xex build; also included an xnotify if it loads successfully when Aurora/FSD is launched. Same link as before... https://github.com/StelioKontosXBL/AuroraCrashPatcher/tree/base-addr-tests/Dist

**Comment by ghost** [comment] 2021-04-25 17:03
Hi @StelioKontosXBL  no, is not working. I will go instead with liveblock and livestrong ON. I won't get the full information but the boxart will be ok. Thanks for everything.

Hopefully with a new aurora released version this will be fixed.

**Comment by Ste1io** [comment] 2021-04-25 20:12
@danielTobon43 @Makein turns out the cause for it not working for you is having LiveBlock/LiveStrong enabled. If you have a stealth set in your plugins and disable LiveBlock/LiveStrong, the plugin will work as intended. I'll push an update to account for this. Thanks again for your help.

**Closed as completed by Ste1io** 2021-04-25 20:12 UTC
